name: Local Dev Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    name: "Local Dev Build"
    runs-on: ubuntu-latest
    env:
      APP_ENV: "development"
    steps:
      - name: "checkout main"
        uses: actions/checkout@v4

      - name: "Setup EAS"
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest

      - name: "Setup Node"
        uses: ./.github/actions/setup-node-pnpm-install
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "17"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Test APK
        run: |
          pnpm prebuild:${{ APP_ENV }}
          cd  android
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon
          cd ..
        shell: bash

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
